global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: "monitoring-demo"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'
#   # - "first.rules"
#   # - "second.rules"

# # alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

scrape_configs:
  # - job_name: 'prometheus'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 5s

  #   static_configs:
  #        - targets: ['localhost:9090']

  - job_name: 'metric_server'
    scrape_interval: 10s # Override the global default and scrape targets from this job every 5 seconds.
    static_configs:
      - targets: ['evidently_service.:8085']
